version: 2
updates:
  - package-ecosystem: cargo
    cooldown:
      default-days: 7
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - synmux
  - package-ecosystem: docker
    cooldown:
      default-days: 7
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - synmux
  - package-ecosystem: github-actions
    cooldown:
      default-days: 7
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - synmux
