[package]
default-run = "belt"
description = "A CLI toolbelt"
edition = "2024"
license = "MIT"
name = "belt-cli"
publish = false
readme = "README.md"
repository = "https://github.com/synmux/belt"
version = "0.0.0-pre.0"

[dependencies]
bip39 = { version = "3.0.0", features = ["serde"] }
blake2 = "0.11.0"
clap = { version = "4.6.7", features = [
  "derive",
  "env",
  "unicode",
  "wrap_help",
  "string",
  "suggestions",
  "error-context",
  "help",
  "usage",
  "color",
] }
clap_complete = "4.6.11"
clio = { version = "0.3.5", features = ["clap", "clap-parse"] }
crossterm = { version = "0.29.0", features = ["serde", "osc52"] }
ratatui = { version = "0.30.2", features = [
  "serde",
  "palette",
  "scrolling-regions",
  "crossterm",
] }
shadow-rs = { version = "2.0.0", features = [
  "cargo_metadata",
  "document-features",
  "serde_json",
  "metadata",
] }
ur = "0.5.2"

[[bin]]
name = "belt"
path = "src/main.rs"

[build-dependencies]
clap_mangen = "0.3.3"
