[env]
BELT_MISE_ACTIVE = 'true'

[settings]
env_file = '.env'

[tools]

rust = {
  version = '1.98.1',
  mr_boxington = true,
  profile = 'default',
  components = [
    'rust-docs',
    'rust-src',
    'llvm-tools',
    'clippy',
    'rustfmt',
    'rust-analyzer',
  ]
}

mr-boxington = {
  version = '1.10.0'
}
