check = { overrideCommand = [
  "/Users/syn/Library/Application Support/mbx/bin/cargo",
  "check",
  "--workspace",
  "--all-targets",
  "--target-dir",
  "target/rust-analyzer",
  "--message-format=json",
] }
